version: '3'
services:
  pokedexapi:
    build: .
    container_name: pokedex-api
    ports:
      - 8081:8080
    networks:
      - pokemonnetwork
    environment:
      - APP_PORT=8080
      - APP_HOSTNAME=0.0.0.0
      - NODE_ENV=production
      - DB_USERNAME=root
      - DB_PASSWORD=admin
      - DB_NAME=pokemons
      - DB_HOST=local-mysql

networks:
  pokemonnetwork:
    external: true
